"""Docker feature generator."""

from __future__ import annotations

from mcp_builder.domain.artifacts import ArtifactSpec
from mcp_builder.domain.diagnostics import Diagnostic, Ownership, Severity
from mcp_builder.domain.project import ProjectSpec, StreamableHttpTransport
from mcp_builder.generation.renderer import content_hash

DOCKERFILE = """\
# Generated by MCP Builder Toolkit — managed file.
# Non-root runtime with dependency constraints installed by uv.
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder

WORKDIR /app
ENV UV_COMPILE_BYTECODE=1 \\
    UV_LINK_MODE=copy

COPY pyproject.toml README.md ./
COPY src ./src
RUN uv sync --no-dev

FROM python:3.12-slim-bookworm AS runtime

RUN useradd --create-home --uid 10001 appuser
WORKDIR /app

COPY --from=builder /app /app
ENV PATH="/app/.venv/bin:$PATH" \\
    PYTHONUNBUFFERED=1

USER appuser

{network_env}{expose}
{cmd}
"""


class DockerFeature:
    id = "docker"

    def supports(self, project: ProjectSpec) -> bool:
        return project.features.docker

    def validate(self, project: ProjectSpec) -> list[Diagnostic]:
        diags: list[Diagnostic] = []
        if project.features.docker and project.transport.type == "stdio":
            diags.append(
                Diagnostic(
                    code="MBT-MANIFEST-004",
                    severity=Severity.WARNING,
                    message=(
                        "Docker generation with stdio transport is unusual; "
                        "prefer streamable-http for containerized servers"
                    ),
                    path="spec.features.docker",
                    hint="Set transport.type to streamable-http for remote MCP over HTTP.",
                )
            )
        return diags

    def plan(self, project: ProjectSpec) -> list[ArtifactSpec]:
        if isinstance(project.transport, StreamableHttpTransport):
            port = project.transport.port
            network_env = 'ENV MCP_HOST="0.0.0.0"\n'
            expose = f"EXPOSE {port}"
            cmd = f'CMD ["python", "-m", "{project.project.package_name}.server"]'
        else:
            network_env = ""
            expose = "# stdio: no EXPOSE"
            cmd = f'CMD ["python", "-m", "{project.project.package_name}.server"]'

        content = DOCKERFILE.format(network_env=network_env, expose=expose, cmd=cmd)
        if not content.endswith("\n"):
            content += "\n"
        return [
            ArtifactSpec(
                relative_path="Dockerfile",
                content=content,
                content_hash=content_hash(content),
                ownership=Ownership.MANAGED,
                origin="feature.docker/Dockerfile",
            ),
            ArtifactSpec(
                relative_path=".dockerignore",
                content=_dockerignore(),
                content_hash=content_hash(_dockerignore()),
                ownership=Ownership.MANAGED,
                origin="feature.docker/dockerignore",
            ),
        ]


def _dockerignore() -> str:
    return """\
.venv
.git
.mcp-builder
.pytest_cache
.mypy_cache
.ruff_cache
__pycache__
*.pyc
.coverage
htmlcov
.env
"""
