"""Docker Compose feature generator."""

from __future__ import annotations

import yaml

from mcp_builder.domain.artifacts import ArtifactSpec
from mcp_builder.domain.diagnostics import Codes, Diagnostic, Ownership, Severity
from mcp_builder.domain.project import ProjectSpec, StreamableHttpTransport
from mcp_builder.generation.renderer import content_hash


class ComposeFeature:
    id = "compose"

    def supports(self, project: ProjectSpec) -> bool:
        return project.features.compose

    def validate(self, project: ProjectSpec) -> list[Diagnostic]:
        diags: list[Diagnostic] = []
        if project.features.compose and not project.features.docker:
            diags.append(
                Diagnostic(
                    code=Codes.MANIFEST_SEMANTIC,
                    severity=Severity.ERROR,
                    message="features.compose requires features.docker",
                    path="spec.features.compose",
                )
            )
        if project.features.compose and not isinstance(project.transport, StreamableHttpTransport):
            diags.append(
                Diagnostic(
                    code=Codes.MANIFEST_SEMANTIC,
                    severity=Severity.ERROR,
                    message="Compose generation requires transport.type streamable-http",
                    path="spec.transport.type",
                    hint="Set streamable-http host/port/path for published services.",
                )
            )
        return diags

    def plan(self, project: ProjectSpec) -> list[ArtifactSpec]:
        assert isinstance(project.transport, StreamableHttpTransport)
        host = project.transport.host
        port = project.transport.port
        # Publish only the configured host port; container still listens on port.
        document = {
            "services": {
                "mcp": {
                    "build": ".",
                    "ports": [f"{host}:{port}:{port}"],
                    "environment": {"PYTHONUNBUFFERED": "1"},
                    "restart": "unless-stopped",
                }
            }
        }
        content = (
            "# Generated by MCP Builder Toolkit — managed file.\n"
            "# Port publishing is explicit; do not publish to 0.0.0.0 without review.\n"
            + yaml.safe_dump(document, sort_keys=False)
        )
        return [
            ArtifactSpec(
                relative_path="compose.yaml",
                content=content,
                content_hash=content_hash(content),
                ownership=Ownership.MANAGED,
                origin="feature.compose/compose.yaml",
            )
        ]
